# Generated by Django 4.1.5 on 2023-01-23 17:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0002_rename_address_user_role_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_string', models.TextField()),
                ('year', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('options', models.JSONField(default=None, editable=False, verbose_name='QuestionOptions')),
                ('answer', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRS.category')),
            ],
        ),
    ]
