# Generated by Django 4.1.5 on 2023-01-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0003_category_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(upload_to='uploads/questions/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
