# Generated by Django 4.1.5 on 2023-01-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0004_alter_question_image_alter_question_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/questions/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(null=True, verbose_name='QuestionOptions'),
        ),
    ]
