# Generated by Django 4.1.5 on 2023-01-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0005_alter_question_image_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, null=True, verbose_name='QuestionOptions'),
        ),
    ]
