# Generated by Django 4.1.5 on 2023-01-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0008_alter_category_c_name_alter_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('LG', 'Long Question'), ('SH', 'Short Question'), ('MC', 'Multiple Choice')], default='MC', max_length=2),
        ),
    ]
