# Generated by Django 4.1.5 on 2023-01-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0010_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('LQ', 'Long Question'), ('MC', 'Multiple Choice')], default='MC', max_length=2),
        ),
    ]
