# Generated by Django 4.1.7 on 2023-03-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CRS", "0011_alter_question_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="questioncategory", name="Cid",),
        migrations.DeleteModel(name="Category",),
    ]
