# Generated by Django 4.1.7 on 2023-03-15 08:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("CRS", "0012_remove_questioncategory_cid_delete_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionQuestion",
            fields=[
                (
                    "question_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("statement", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="question", old_name="question_string", new_name="string",
        ),
        migrations.RemoveField(model_name="question", name="answer",),
        migrations.RemoveField(model_name="question", name="question_id",),
        migrations.RemoveField(model_name="question", name="year",),
        migrations.AddField(
            model_name="question",
            name="QID",
            field=models.AutoField(default="00001", primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ALGO", "Algorithm Design"),
                    ("BMO", "Basic Machine Organisation"),
                    ("COM", "Computer System"),
                    ("DM", "Data Manipulation and Analysis"),
                    ("DO", "Data Organisation and Data Control"),
                    ("ELEWEB", "Elementary Web Authoring"),
                    ("HEALTH", "Health and Ethical Issues"),
                    ("INFO", "Information Processing"),
                    ("IP", "Intellectual Property"),
                    ("NETSEV", "Internet Services and Applications"),
                    ("MEDIA", "Multimedia Elements"),
                    ("NETBAS", "Networking and Internet Basics"),
                    ("PROGRAM", "Program Development"),
                    ("SD", "Spreadsheets and Databases"),
                    ("THREAT", "Threats and Security on the Internet"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="description",
            field=models.JSONField(
                blank=True, null=True, verbose_name="QuestionDescription"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="parentQID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="CRS.question",
            ),
        ),
        migrations.DeleteModel(name="QuestionCategory",),
    ]
