# Generated by Django 4.1.7 on 2023-03-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRS", "0013_questionquestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="statement",
            field=models.TextField(blank=True, null=True),
        ),
    ]
