# Generated by Django 4.1.7 on 2023-03-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRS", "0015_alter_question_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="QID",
            field=models.BigIntegerField(
                max_length=6, primary_key=True, serialize=False
            ),
        ),
    ]
