# Generated by Django 4.1.7 on 2023-03-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRS", "0016_alter_question_qid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="QID",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
