# Generated by Django 4.1.7 on 2023-03-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRS", "0018_alter_question_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
