# Generated by Django 4.1.7 on 2023-03-16 11:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("CRS", "0024_rename_type_question_qtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="category",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("ALGO", "Algorithm Design"),
                    ("BMO", "Basic Machine Organisation"),
                    ("COM", "Computer System"),
                    ("DM", "Data Manipulation and Analysis"),
                    ("DO", "Data Organisation and Data Control"),
                    ("ELEWEB", "Elementary Web Authoring"),
                    ("HEALTH", "Health and Ethical Issues"),
                    ("INFO", "Information Processing"),
                    ("IP", "Intellectual Property"),
                    ("NETSEV", "Internet Services and Applications"),
                    ("MEDIA", "Multimedia Elements"),
                    ("NETBAS", "Networking and Internet Basics"),
                    ("PROGRAM", "Program Development"),
                    ("SD", "Spreadsheets and Databases"),
                    ("THREAT", "Threats and Security on the Internet"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
