# Generated by Django 4.1.7 on 2023-03-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRS", "0025_alter_question_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.CharField(default="st0001", max_length=6),
        ),
    ]
