# Generated by Django 4.1.7 on 2023-03-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRS", "0026_questioninput_user_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=6)),
                ("text", models.TextField()),
                ("result", models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
