# Generated by Django 4.1.7 on 2023-03-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRS", "0027_questioninput"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questioninput",
            name="uid",
            field=models.CharField(default="st0001", max_length=6),
        ),
    ]
